google_analytics:
  tracker_id: 'UA-12345-67'

disqus:
  account: 'gonow'
  default_tab: 'popular'
  color: 'grey'
  hide_mods: true
  num_items: 10
  show_powered_by: true
  developer: true

paginate:
  per_page: 5
